
server:
  port: 8084
spring:
  application:
    name: borrow-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
feign.httpclient.enabled: true
properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL91Dialect
