
server:
  port: 8084
spring:
  application:
    name: book-service
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123456
#    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://localhost:3306/jwtsecurity
    username: root
    password: 18081997
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

feign:
  httpclient.enabled: true
  okhttp.enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
client:
  post:
    borrow: 'http://localhost:8089'

#properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL91Dialect
properties.hibernate.dialect: org.hibernate.dialect.MySQL5DiaLect