
server:
  port: 8085
spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

feign:
  httpclient.enabled: true
  okhttp.enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
client:
  post:
    borrow: 'http://localhost:8089'

properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL91Dialect

