server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: category-service
          uri: http://localhost/8082
          predicates:
          - Method=GET,POST,PUT
        - id: book-service
          uri: http://localhost/8083
          predicates:
          - Method=GET,POST,PUT
        - id: borrow-service
          uri: http://localhost/8089
          predicates:
          - Method=GET,POST,PUT
        - id: transaction-service
          uri: http://localhost/8085
          predicates:
          - Method=GET,POST,PUT
        - id: lost-service
          uri: http://localhost/8086
          predicates:
          - Method=GET,POST,PUT
