server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8088/
          predicates:
            - Path=/users/**
            - Method=GET,POST,PUT,DELETE
        - id: category
          uri: http://localhost:8082/
          predicates:
            - Path=/categories/**
            - Method=GET,POST,PUT,DELETE
        - id: book
          uri: http://localhost:8084/
          predicates:
            - Path=/books/**
            - Method=GET,POST,PUT,DELETE
        - id: borrow
          uri: http://localhost:8089/
          predicates:
            - Path=/borrows/**
            - Method=GET,POST,PUT,DELETE
        - id: transaction
          uri: http://localhost:8085/
          predicates:
            - Path=/transactions/**
            - Method=GET,POST,PUT,DELETE
        - id: lost
          uri: http://localhost:8086/
          predicates:
            - Path=/losts/**
            - Method=GET,POST,PUT,DELETE
        - id: auth
          uri: http://localhost:8087/
          predicates:
            - Path=/auth/**
            - Method=GET,POST,PUT,DELETE
