
server:
  port: 8088
spring:
  application:
    name: transaction-service
  datasource:
    #    url: jdbc:postgresql://localhost:5432/postgres
    #    username: postgres
    #    password: 123456
    #    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://localhost:3306/jwtsecurity
    username: root
    password: 18081997
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

#properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL91Dialect
properties.hibernate.dialect: org.hibernate.dialect.MySQL5DiaLect



